### ISSUE TITLE
Memory leak in `BitmapTable`?

### ISSUE THREAD

**Issue by tyskwo** [finnvoor/PlaydateKit#96] opened 2024-10-19 01:12 UTC
Using the following A/B example, I'm seeing a 40 byte heap allocation every frame in (A), whereas there is no such allocation in (B). Both path exists, and the table has multiple frames. It seems that the memory leak size is not related to the number of frames. To my knowledge, the Playdate's API uses `BitmapTable` within its font rendering calls, and I'm seeing similar memory leaks when referencing fonts.

```
(A)
let b: Graphics.Bitmap = try! Graphics.Bitmap(path: "sample.png")
Graphics.drawBitmap(b, at: Point(x: 100, y: 50), degrees: 0, center: Point.zero)

(B)
let t: Graphics.BitmapTable = try! Graphics.BitmapTable(path: "sampleTable.png")
Graphics.drawBitmap(t[0]!, at: Point(x: 200, y: 50), degrees: 0, center: Point.zero)
```

Issue still occurs if we wrap `t[0]!` in an `if let`.

**Comment by tyskwo** [comment] 2024-10-19 15:09
Similar allocations can be seen in the Pong example too, and I believe these are stemming from the text draws for the score, since the sprites used don't load bitmaps, and instead rely on the primitive geometry draws supplied by the SDK. (In my experience, the bitmap-oriented allocations are always 40 bytes (probably related to the `OpaquePointer` if I had to posit a guess), whereas the font allocations are typically >40 bytes, which I assume is also allocating a copy of the string.)

**Comment by finnvoor** [comment] 2024-10-24 21:11
Seems like this is caused by a bug in the latest Swift toolchain, and will be fixed whenever the next nightly toolchain is released (see https://github.com/swiftlang/swift/pull/77121)

**Closed by finnvoor** 2024-10-24 21:11 UTC
